### PR TITLE
Update to 1.12

### PR DESCRIPTION
**Pull request by AEnterprise**
Update complete, some parts still need polishing (recipes for dissabled items/blocks can probably be handled better, not all recipes are moved to json yet and advancements are not finished yet)

but other then the polishing everything works (also includes the fixes included in #3753 )

### CODE REVIEW

**Comment by AEnterprise** [comment]
and this should be ready for review as well, the only thing that's not done are advancements but those are minor compared to the other changes and can be done in paralel

**Comment by mcsnetworks** [comment]
Any idea when this will be pulled?

**Comment by LuigiHutch** [comment]
Probably after the JSON guis pr is merged and when Alex feels it's time. Be patient

**Comment by AEnterprise** [comment]
ETA on this is very tricky as there are some massive changes in here so the other devs need time to be able to do a decent review of these

**Comment by Dockter** [comment]
If you need help testing be sure to ping me.

**Comment by Tencao** [comment]
I've been testing all the commits here for a few weeks now however the last few commits merging the upstream seems to have caused a weird null being stored in NBTTagCompound. This doesn't appear in single player but sponge detected it and outputted the trace for me.

Crash/Trace - https://paste.ee/r/o7i6f
https://github.com/AEnterprise/BuildCraft/blob/1.12/common/buildcraft/lib/misc/JsonUtil.java#L423
https://github.com/AEnterprise/BuildCraft/blob/1.12/common/buildcraft/builders/snapshot/RulesLoader.java#L108

**Comment by AEnterprise** [comment]
thanks for reporting, this is indeed something that heapens but i am not 100% sure of the exact cause (note people reported this for 1.11.2 as well). It seems somewhere a block is eluding our safety checks and causing invalid data storage like this. Sadly i have not been able to trace any blocks doing this (heapens in different related places in the code) to be able to test and patch this

**Comment by Tencao** [comment]
If it helps I have very limited buildcraft blocks placed in my world, and the only one with tile data is the quarry we was testing which had 0% progress building the frame and no power fed to it.

**Comment by AEnterprise** [comment]
i'll try to look into this again later, this spongereport included the key we are saving with a null value, all the others that reported this just said this heapened randomly (on a server with multiple people and no sponge) so who and what exactly triggered it was never easy to trace

**Comment by AlexIIL** [comment]
> note people reported this for 1.11.2

Where? This sounds like something that needs looking at before 7.99.8...

**Comment by AEnterprise** [comment]
as talked about on discord: i was thinking about a different bug that is similar but not the same

**Comment by Tencao** [comment]
Just like to say the recent null commits, including the latest one that wasn't merged with this still has this same crash. If you'd like me to make an issue report out of this instead I can do.
https://github.com/BuildCraft/BuildCraft/commit/2ba962336cca4dab7dc39706b75321faa0b5c637

**Comment by AEnterprise** [comment]
pulled in the most recent commits, if that still crashes you please make a seperate issue for keeping track

**Comment by Tencao** [comment]
Done and still crashes. Made an issue here - #3831

**Comment by FUZIK** [comment]
how long will it take for me to update?

**Comment by AEnterprise** [comment]
what do you mean for you to update?
if you wana know when it's gona be released then we don't have an eta at this time

if you want to help there is little you can do right now but wait, the other devs are currently looking at it

**Comment by AlexIIL** [comment]
I'm working on this separately now, I'll probably just push straight to 8.0.x when I'm done.

**Comment by Tencao** [comment]
I do want to say from testing no major bugs has been present on the last 1.12 build

**Pull request closed without merging**
