### PR TITLE
Create/Add Jenkinsfile for Automatic Builds

### PR DESCRIPTION
**Pull request by Flow86**
I've added a Jenkinsfile for automatic builds on a new 2.x jenkins.

Here's the PR for that if you want to use such a feature again.

Jenkins only needs the "Docker pipeline" plugin. Node should also be configured to run docker containers. (Otherwise one has to remove the "withDockerContainer"-block)

Best combined with "GitHub Organization Folder Plugin",  then you can set up a "GitHub Organization Pipeline"-Project. 

All PRs and Branches are then build automatically if they have a Jenkinsfile.

Hope its helpful ;-)

### CODE REVIEW

**Comment by AEnterprise** [comment]
has this been tested with such a new jenkins server? also would this affect an older jenkins building (i presume not but don't know much about jenkins)

**Comment by Flow86** [comment]
yes the build script works on my jenkins server.

**Comment by AEnterprise** [comment]
paging @AlexIIL for this then if he wants to support automated jenkins builds with this.

side question: could your jenkins be used for alpha builds in a later stage by chanse? it's not usable yet but people keep asking for it so would be good to have something setup ahead of time

**Comment by Flow86** [comment]
yes would be possible to use. the one provided on the nallar.me website is not usable anymore?

**Comment by AEnterprise** [comment]
nope, no idea who runs that one and BC has been deactivated on it

**Comment by Anora** [comment]
if your looking for a spot to run a Jenkins on I have a server I could possibly lend some space on

**Comment by AEnterprise** [comment]
@Flow86 it seems that your jenkins is now as check but there is a problem with that: a login is required to access it so the build failed yet we have no idea why, making the pr integration kinda useless

**Comment by Flow86** [comment]
anonymous access should be available now

**Comment by AlexIIL** [comment]
This will be quite useful in the future, but until we reach proper testing stages I'm not sure if its a good idea to publish build artifacts.

**Comment by AEnterprise** [comment]
it would alteast be great for pr's and i thought that a first alpha version was getting close or am i wrong in that?

2 of the automated test seem to have broken as well and need updating/fixing, most likely due to some of the MC networking changes

**Comment by AlexIIL** [comment]
Makes sense. Also the tests are newer tests that I've fixed in my local branch, so they aren't something to worry about.

**Comment by AEnterprise** [comment]
well can i sugest them to be fixed on the repo here soon then we can see in the future if the jenkins realy fail or not?

**Comment by AlexIIL** [comment]
It looks like they were fixed in https://github.com/BuildCraft/BuildCraft/commit/8f76be04e6f11c7b809561b679c4f9973be0578b, this PR just didn't update to that commit as it didn't need to

**Comment by AEnterprise** [comment]
should have checked that, sorry :/

**Comment by AlexIIL** [comment]
... turns out I was wrong. Actually fixed in https://github.com/BuildCraft/BuildCraft/commit/bfa45888417c181ca1ea8dc854ef4c67fd230691.

**Comment by nallar** [comment]
@AEnterprise it's not hard to find out :P

**Pull request merged**
