### PR TITLE
Change references to capacity to getCapacity()

### PR DESCRIPTION
**Pull request by da3dsoul**
for ease of overriding.

### CODE REVIEW

**Comment by asiekierka** [comment]
Why?

**Comment by da3dsoul** [comment]
ABO has reinforced pipes with a higher capacity and flow. The current setup either needs capacity to be protected, or to reference the getCapacity method. As of now, the absolute maximum flow is 250 mB per pipe section due to the internal mechanics of PipeTransportFluids, with no easy way to increase it.

**Comment by asiekierka** [comment]
The absolute maximum flow is intended as I optimized the fluid update packet protocol to send the amount as a byte rather than a short. This needs to be rethought.

**Comment by da3dsoul** [comment]
I see.

**Pull request closed without merging**
