### PR TITLE
compilation fixes

### PR DESCRIPTION
**Pull request by AEnterprise**
more work towards getting BC to a compiling state

### CODE REVIEW

**Comment by AlexIIL** [comment]
[reply to eclipse problems]
Ok, so you need to do 2 things:
1 pick a workspace location (can be anywhere)
2 run gradle eclipse
3 import the BC folder

**Comment by AEnterprise** [comment]
did that, doing it again in a new folder with a fresh clone, i suspect intellij got in the way and messed it up

**Comment by AEnterprise** [comment]
alright got it working, apearently eclipse is stupid and just refused to launch cause i didn't have a file opened >.<

**Comment by AEnterprise** [comment]
so should i fix the merge conflicts did you fix these files already?

**Comment by AEnterprise** [comment]
no longer needed so closing

**Pull request closed without merging**
