### PR TITLE
Item Transport Pipe improved aesthetics

### PR DESCRIPTION
**Pull request by MoreThanHidden**
Related to: AlexIIL/Buildcraft_1.8_Issues#55 and #3200
Improved item movement.

### CODE REVIEW

**Comment by asiekierka** [comment]
Wait. Why did AlexIIL touch the item movement logic to begin with?

**Comment by AlexIIL** [comment]
@asiekierka when I was porting it to begin with. (I changed a bunch of stuff to Vec3 and broke everything)

**Comment by AlexIIL** [comment]
Anyway, this only half works- now items travelling vertically don't  work.

**Comment by MoreThanHidden** [comment]
> Anyway, this only half works- now items travelling vertically don't work.

Not sure why that is they are working in my tests...

**Comment by AlexIIL** [comment]
For some reason items are vanishing for a small section. I have no idea what causes that but I don't think that it is this.

**Comment by AlexIIL** [comment]
I added something like this a while ago, so now the item vanishing problem is smaller than before.

**Comment by MoreThanHidden** [comment]
Yeah sorry haven't had a chance to look into thoroughly, comparing with 7.1 a couple of the comparisons are greater-than rather than less-than ext. (currently working on my own "broken aspect ratio" issues for another mod :P) but I'll take a look when I can, if you haven't already fixed it.

**Pull request closed without merging**
