### PR TITLE
New Features: Add BC Villager and Void Kenesis Pipe

### PR DESCRIPTION
**Pull request by warlordjones**
Base work for #1945 

Very few trades as yet, I need ideas for more. He needs a home too.

### CODE REVIEW

**Comment by AEnterprise** [comment]
he won't spawn without a home, also could you maybe use the BC code style and mainly then the import settings? makes it easier as that way we don't have to scroll through the moved imports, and a squash would be easy

**Comment by warlordjones** [comment]
I'm going to implement a home soon, I would suggest not merging this get.

I'll use the BC code style from now on.

Arona
[+] You're welcome to add me to your address book
<https://ws.writethat.name/kwaga-bin/titan/WEB/me.pl/2040834221374130777/i>

**Comment by AEnterprise** [comment]
ok, if you need help or an example i sugest taking a look at the BCA powerplant code

**Comment by hea3ven** [comment]
Also, if statements should be surrounded by braces even if it is only 1 line. You can run "gradle checkstyleMain" to see any style errors, there may be some errors from before, just try not to add to that list :).

**Comment by warlordjones** [comment]
@AEnterprise I'm able to do the codeside part, I just need the building itself ;)

@hea3ven Ty :)

**Comment by warlordjones** [comment]
Void Kenesis pipe semi works - it voids any power trying to travel through it, but doesn't itself request energy.

**Comment by warlordjones** [comment]
I ran a formatter profile across the repo based off the checkstyle configuration - feel free to shout at me if there are problems

**Comment by Kubuxu** [comment]
As far as I know BC uses Tabs and I noticed few cases where Spaces were used for indentation.

**Comment by AEnterprise** [comment]
@warlordjones BC style used tabs, you just replaced all tabs with spaces, please fix that

**Comment by hea3ven** [comment]
@warlordjones don't reformat the whole repo, it breaks git blame. Also It's a different style than what it currently is, changing tabs for spaces, reducing the line length, removes spaces before certain operators.

**Comment by warlordjones** [comment]
Argh, sorry! I'll revert that, and leave as it was now.

**Comment by warlordjones** [comment]
I failed at reverting

**Comment by asiekierka** [comment]
Me likey, however:
1. You should squash the commits.
2. I don't think the sounds.json should be here.
3. You might want to consider having BC villagers sell other things too, but I can't think of anything that would fit.
4. Consider trying to make the Void Kinesis Pipe configurable (in the same way the Iron Kinesis Pipe is).

Once all four are replied to and/or complied with, I will merge.

**Comment by warlordjones** [comment]
1. ok, can do
2. yeah, that got caught up this and is for a future PR
3. I will add more sales as I think of them
4. How do you mean configurable
5. Don't merge until I've given the villager a home, he won't spawn
otherwise.

Arona
[+] You're welcome to add me to your address book
<https://ws.writethat.name/kwaga-bin/titan/WEB/me.pl/2040834221374130777/i>

**Comment by warlordjones** [comment]
Perhaps the villager could sell building materials like Sand, Cobblestone, Bricks etc, like he is a 'building materials supplier'?

**Comment by hea3ven** [comment]
Some ideas for trades:
 * pipe sealant for emeralds (easy trade to farm emeralds, similar to the vanilla trade of paper for emeralds)
 * transport pipe + emeralds for fluid pipe
 * emeralds for oil bucket (this would make it posible, because of the fuel trade, to buy oil with emeralds, process it with a refinary and then sell the fuel with an emerald profit)

**Comment by warlordjones** [comment]
Ooh, I like ideas one and two, not sure there is a point in idea two.

**Comment by hea3ven** [comment]
It's more of a filler trade, there's many trades that I doubt anyone uses, like gravel + emeralds = flint. Plus, it kind of fits a lore. I.e. you give the villager a pipe and some money and he "installs" the sealant he got from the other trade in the pipe. Also, I meant it as multiple trades, gold pipe + emerald = gold fluid pipe, wooden pipe + emerald = wooden fluid pipe.

You could make a post in the forums, as you might get more ideas from users that don't come to github.

**Comment by warlordjones** [comment]
Will do.

**Comment by asiekierka** [comment]
Buying Basic Gates from Villagers?

**Comment by warlordjones** [comment]
Yup, I think so, that was also suggested over at the forums

**Comment by AEnterprise** [comment]
just a sugestion but as long as you're not using power pipes you also could make the structure in a world, make a blueprint out of it and use the blueprint deployer to build it, i threw it out of BCA cause of powerpipes i think but also possible there was another minor thing, i'll see if i can find it

**Comment by asiekierka** [comment]
Villager in separate repo. Void Kinesis will be rewritten or scrapped.

**Comment by warlordjones** [comment]
Ok.

**Pull request closed without merging**
