### PR TITLE
fix fluid dupe with the pump robot

### PR DESCRIPTION
**Pull request by hea3ven**

### CODE REVIEW

**Comment by asiekierka** [comment]
Barely caught it, thanks!

(You really should get set up into the BC contributors group. I sent you an invite once but you say you never received it.)

**Comment by hea3ven** [comment]
I am, should I just push bug fixes directly to the repo?

**Comment by KamranMackey** [comment]
@hea3ven: Yes.

**Comment by asiekierka** [comment]
@hea3ven: Yes. Generally, I trust you enough just to push in anything but behaviour changes/feature additions - consult these with me beforehand.

**Pull request merged**
