### PR TITLE
Update TileAutoWorkbenchBase.java

### PR DESCRIPTION
**Pull request by AlexIIL**

### CODE REVIEW

**Comment by AlexIIL** [comment]
Fixes #3721

**Comment by AlexIIL** [comment]
(Done as a PR so that travis can check to see if I've messed something up)

**Comment by AEnterprise** [comment]
fine but you are suposed to be enjoying your time away, i fixed this on 1.12 already and was gona backport any fixes i do in the next weeks all at once

so if you realy want to fix things without dev environment go ahead but make sure you don't do to much or worry about the bugs in your off time

**Comment by AlexIIL** [comment]
You *almost* fixed it - it could have still thrown an NPE when running the integrated server.

Don't worry about my holiday - it has plenty of downtime when I've got nothing better to do.

**Comment by AEnterprise** [comment]
my fix was basicly a null check so wouldn't have crashed but this fix is fine as well

**Comment by AlexIIL** [comment]
The issue with your fix is that you checked to see if it was null, then used the variable if it wasn't null. This would be fine in a single threaded environment, but in multithreaded environments (like when the client thread is reading data from the server thread) the server thread might have changed the variable in between the check and the access. (It seems unlikely, but it can happen. It's more likely to happen with other blocks that change between null and a value each tick, especially as it's being called every frame)

**Comment by AlexIIL** [comment]
(This is also why I wanted to fix this myself while the problem was fresh in my mind - it's unlikely that's I would have noticed the issue with your fix at first, as it looks fine by default)

**Comment by AEnterprise** [comment]
oh right, well thanks for spotting then :P

**Pull request merged**
