### PR TITLE
Clean up imports and fix item lighting

### PR DESCRIPTION
**Pull request by KitsuneAlex**
Cleaned up a ton of unused imports and fixed item lighting for pipes, engines and other blocks

### CODE REVIEW

**Comment by AlexIIL** [comment]
Import cleanup isn't very useful unfortunately - can you please revert the import changes and preserve just the item lighting fixes? I can't really review the item changes amongst the 707 changed files .

**Comment by AlexIIL** [comment]
(For future reference, imports are ordered according to https://github.com/BuildCraft/BuildCraft/blob/8.0.x/guidelines/buildcraft.checkstyle#L20 and star imports are disallowed as they can break stuff when multiple classes exist with the same name)

**Comment by KitsuneAlex** [comment]
yeah makes sense, sorry man, already on it!

**Comment by AEnterprise** [comment]
what issues with item lighting would this fix? could you get some before and after screenshots?

**Comment by AEnterprise** [comment]
also out of curiousity i let intellij do a check to trace unused imports, almost all those files (507/551) are files under the old license that are not being used, if you want i can fix those and push it here @AlexIIL or leave it as is since it doesn't break anything and intellij will 'fix' those imports anyways next time any of us work on one of those files

**Comment by KitsuneAlex** [comment]
Before/After http://imgur.com/a/8IhOf

**Comment by AlexIIL** [comment]
@AEnterprise I'll handle src_old_license separately.

**Comment by AEnterprise** [comment]
@KitsuneAlex thanks that looks good in the picture

@AlexIIL thought you might wanted to do that, i'll just leave as is and just leave it to intellij to clean up when i'm working on parts of the code

**Comment by KitsuneAlex** [comment]
alright, ill just revert the cleanup, didn't really know that it was old stuff, sorry for that
ill commit the lighting thing in another PR

**Comment by AEnterprise** [comment]
any update on this?

**Comment by KitsuneAlex** [comment]
yeah sorry, i was busy, will PR later

**Pull request closed without merging**
