### PR TITLE
Finally fixed #3503

### LINKED ISSUE #3503: BC 7.1.20 AutoWorkbench Dupe (NBT checking)
AutoWorkbench does not compare NBT items.
https://www.youtube.com/watch?v=rfqad_-kMmY&t=2m26s

I fixed it activating the check here: https://github.com/BuildCraft/BuildCraft/blob/7.1.x/common/buildcraft/factory/TileAutoWorkbench.java#L340

Why don't you use **ItemStack.areItemStackTagsEqual()** in here?
https://github.com/BuildCraft/BuildCraft/blob/7.1.x/common/buildcraft/core/lib/inventory/StackHelper.java#L205-L207
If the first item is missing NBT, it will return true, which is not good.

### PR DESCRIPTION
**Pull request by usernameak**
Now it really isn't dupeable.

### CODE REVIEW

**Comment by AlexIIL** [comment]
I haven't booted into a 1.7.10 workspace for quite a while... so it may take a while for me to validate this (sorry)

**Comment by AlexIIL** [comment]
That being said I'm really not sure how also validating NBT could be harmful...

**Comment by asiekierka** [comment]
Leave this for review for me. I'm unable to do it today, I'll do it tomorrow.

**Comment by asiekierka** [comment]
I *think* there is a reason I made it that way. Will have to investigate as it was a long, long time ago.

**Comment by AEnterprise** [comment]
travis build is failing but is unrelated to the PR changes, somehow the JDK is choking internaly on establishing an https connection to pull in gradle

**Comment by asiekierka** [comment]
@usernameak Can you provide a reproduction scenario?

**Comment by usernameak** [comment]
@asiekierka look at the video in #3503 . Note that you have to split cobble stack in two otherwise it won't work.

**Comment by asiekierka** [comment]
Checked the video. The issue shown in the video is not reproducible in 7.1.23 - the auto workbench still operates, but the recipe output is correct for the *supplied* items, not the fake "configured" items.

**Pull request closed without merging**
