### PR TITLE
Make slimeball recipe work with oredict. Close #2551.

### LINKED ISSUE #2551: oredict slime balls recipe
The slime balls -> pipe sealant should use ore dict to allow slime balls from other mods to be used.

### PR DESCRIPTION
**Pull request by Kubuxu**

### CODE REVIEW

**Comment by Kubuxu** [comment]
Or should I add it to 6.5.x branch?

**Comment by asiekierka** [comment]
What, from other mods, is oredicted under slimeball?

**Comment by Kubuxu** [comment]
From TiC blue slime ball.

**Comment by Silwing** [comment]
I also think MineFactory Reloaded's pink slimeballs are. And maybe TiC coagulated blood.

**Comment by BigXplosion** [comment]
IC2 rubber and some other things that are sticky/glue related are registered as a slimeball I think

**Comment by Sandriell** [comment]
The original recipe as added is bugged as well. It is looking for slimeballs with a damage value of "2", which of course does not exist.

**Comment by Kubuxu** [comment]
Oh I screw up with a push. Fixing now.

**Comment by asiekierka** [comment]
After thought, I decided I don't really trust mod ore dictionaries enough to allow for this. However, support for TCon/etc slimeballs will go into BuildCraftCompat.

**Comment by Kubuxu** [comment]
If we tell the community that slimeballs are alternative recipe for pipe sealant they will expect all slime balls to work. Also current recipe is not working.

**Pull request closed without merging**
